global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      # - targets: ["docker.for.mac.host.internal:8080"] For Mac
      - targets: ["docker.for.win.host.localhost:8080"] # For Windows
